name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.21.0'
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCF_TEST=ON -DCF_BENCH=ON
      
      - name: Build
        run: cmake --build build -- all test format tidy
